sudo: required

language: generic

env:
  OS: linux

services:
  - docker

install:
  - sudo apt-get update
  - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get install docker-ce
  - docker version

before_script:
  - ls -lah

script:
  - docker build -t michaeltigr/zebra-selenium-travis:latest .
  - docker login --username $HUB_USERNAME --password $HUB_PASSWORD
  - docker push michaeltigr/zebra-selenium-travis:latest
